### ISSUE TITLE
question: does Elastic Runtime have APIs to automate the process

### ISSUE THREAD

**Issue by sidd-harth** [pivotal-cf/terraforming-gcp#46]
I am trying to understand how installation of PCF on GCP can be done by Terraforming-GCP. After going through available documentation. I understood it involves 4 steps,

1. Prepare GCP env,
2. Install Ops Manager,
3. Install Bosh Director,
4. Install Elastic Runtime

As far as i understand using these Terraform scripts we can automate(correct me if I am wrong),

1. Prepare GCP env
2. Install Ops Manager

So do we have any APIs(provided by Pivotal) for Elastic Runtime? To create any kind of automated scripts for Elastic Runtime installation.

I searched in Pivotal docs & couldn't find them. Any help is appreciated.

**Comment by genevievelesperance** [comment]
Hi @sidd-harth, for those steps you are expected to use Ops Manager. If you want to automate interactions with ops manager to do steps 3/4, I believe there is a CLI (not supported) used by the release engineering team - https://github.com/pivotal-cf/om

As we are the infrastructure team, we do not use that tool and since it is unrelated to these templates, I'll close this issue. You can reach out on that repo for Ops Manager/ERT questions.
