### ISSUE TITLE
Discussion: NAT boxes?

### ISSUE THREAD

**Issue by ljfranklin** [pivotal-cf/terraforming-gcp#68]
Hi Infrastructure team! We currently have all our VMs in GCP assigned public IPs so they can talk out to the internet. It seems like a production environment would be more likely to setup a few NAT boxes to allow VMs without a public IP to talk out to the internet. Looks like terraforming-aws already follows this pattern. What are your thoughts on updating all the `terraforming-*` repos to use NAT boxes?

**Comment by evanfarrar** [comment]
We could consider providing an option to enable NAT, but it is sort of hard to recommend that wholeheartedly because GCP does not provide any sort of maintained NAT. On the other hand, GCP does not charge for ephemeral public IPs. NAT on AWS is possibly partially done because of security concerns but also has a lot to do with the sheer price of several hundred public IPs on AWS.

For these reasons, the reference architecture for PCF on GCP recommends NATless if possible, but also outlines two other NAT based options. 
https://docs.pivotal.io/pivotalcf/2-0/refarch/gcp/gcp_ref_arch.html#arch_diagram

**Comment by ljfranklin** [comment]
@evanfarrar interesting, didn't realize that "everything gets a public IP" was our recommended approach on GCP. Still a little surprising given the security implications but the doc is pretty clear: "Providing each PCF VM with a public IP address is the most recommended architecture, because of increased latency due to NATs as well as extra maintenance required for NAT instances that cannot be deployed with BOSH."

I'll close this out as my goal was to make sure we're following the reference architecture in CI. Turns out we are, I guess...
