### ISSUE TITLE
Error thrown if dns_suffix variable includes trailing dot

### ISSUE THREAD

**Issue by mattysweeps** [pivotal-cf/terraforming-gcp#89]
The variable `dns_suffix` assumes the trailing dot is not included. If the dot is applied, say with the value `example.com.`, the following error occurs:

```
Error: Error applying plan:
1 error(s) occurred:
* google_dns_managed_zone.env_dns_zone: 1 error(s) occurred:
* google_dns_managed_zone.env_dns_zone: Error creating DNS ManagedZone: googleapi: Error 400: Invalid value for 'entity.managedZone.dnsName': 'example.com..', invalid
```

Notice the `..`. I assumed that `dns_suffix` should be a true suffix to a FQDN. 
Once I updated from `example.com.` to `example.com`, the plan worked.

Thoughts for potential solution:

1. The documentation should explicitly specify to not include the trailing dot (This makes the most sense to me)
2. Usage of the dns_suffix variable should check for the trailing dot

**Comment by cdutra** [comment]
Hi @mattysweeps, thanks for reporting this issue. We decided to update the documentation to warn users that they should not use trailing dots on `dns_suffix`.
The reasoning behind not doing checks for trailing dots is because we use in multiple places and that will add unnecessary complexity.

cc @ciriarte

**Comment by mattysweeps** [comment]
Thanks @cdutra,

Sounds good to me :)
